#!/usr/bin/env bash
# Generate machine-local .muse/hooks.json (AIR-54 S3 follow-up: portability).
#
# muse requires hook commands as ABSOLUTE paths (it does not resolve them
# against the repo root), so hooks.json cannot be committed with a portable
# path. This script materializes it per machine: the template (structure)
# lives here in version control, the generated file is gitignored.
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
OUT="$REPO/.muse/hooks.json"
TMP="$OUT.tmp"

mkdir -p "$REPO/.muse"
jq -nc --arg cmd "$REPO/hooks/muse_memory_inbox.sh" '{
  "_comment": "AIR-54 S3: muse memory write gate (MACHINE-LOCAL, generated by hooks/setup-muse-hooks.sh — do not hand-edit; re-run the script after clone/move). add_memory/edit_memory are diverted to the inbox by the hook script (absolute path required — muse does not resolve relative hook commands against the repo root). Consolidation consumes the inbox into the pool. CC-style format (matcher + hooks[].type=command) verified against muse 1.0.3.",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "add_memory|edit_memory",
        "hooks": [{ "type": "command", "command": $cmd }]
      }
    ]
  }
}' > "$TMP" && mv "$TMP" "$OUT"
echo "wrote $OUT"
