#!/usr/bin/env python3
"""
Deploy bundled AGENTS.md to non-Claude harnesses.

Bundles ai-development-guide.md (guide) + rules with matching harness-scope
frontmatter -> writes to ~/.zcode/AGENTS.md, ~/.config/opencode/AGENTS.md,
~/.codex/AGENTS.md.

Claude (~/.claude/CLAUDE.md) is NOT touched -- it stays symlink to the
slim guide; Claude gets rules via ~/.claude/rules/ auto-load.

Rule classification is auto-discovered from per-rule frontmatter:
    ---
    harness-scope: neutral
    ---
Scopes: neutral | claude-specific | meta

Default bundles 'neutral'. New rules without an explicit harness-scope
default to 'neutral' (generic knowledge defaults to cross-harness). Rules
that are Claude-specific must declare `harness-scope: claude-specific`
explicitly to be excluded from the bundle.

Broken-ref guard: scans every neutral rule's markdown links; if a neutral
rule links to a claude-specific rule, the deploy aborts with an error
listing each broken ref. This forces fixing the ref (or re-scoping the
target) before the bundle ships -- non-Claude readers would otherwise hit
a dead link. Parenthetical Claude notes `(Claude: ...)` are exempt, since
those are Claude-side pointers that non-Claude readers can ignore.

Bundle slimming: rule bodies may mark sections to drop from the bundle with
    <!-- bundle: skip-start --> ... <!-- bundle: skip-end -->
Claude reads the full file via ~/.claude/rules/ symlink; non-Claude bundles
get the slimmed version. No-op for rules without markers.

Size gate: non-Claude harnesses truncate the single AGENTS.md silently.
ZCode truncates at 102,400 bytes (100KiB, hardcoded in zcode.cjs -- no
config). The bundle carries a hard-fail limit of 90KiB (92,160 bytes),
leaving headroom below the truncation line. Over the limit -> abort with
guidance: slim rules/ (encoder-philosophy) or demote on-demand-grade
content to a reference skill (rule keeps an always-on core + pointer).
Precedents: acceptance-evidence / lsp-navigation / instruction-writing
rule+skill pairs.

Run after editing rules/ (deploy discipline in rules/AGENTS.md). Idempotent.
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
GUIDE = REPO / "ai-development-guide.md"
RULES_DIR = REPO / "rules"

TARGETS = [
    pathlib.Path.home() / ".zcode" / "AGENTS.md",
    pathlib.Path.home() / ".config" / "opencode" / "AGENTS.md",
    pathlib.Path.home() / ".codex" / "AGENTS.md",
]

# ZCode truncates a single instruction file at 100KiB (102,400 bytes,
# hardcoded; OpenCode/Codex limits unverified). Keep the bundle under 90KiB
# so tail rules never land in the silent-truncation zone.
BUNDLE_MAX_BYTES = 90 * 1024

# Appended as the bundle's last line; a deployed file whose tail lacks it was
# cut short (or hand-edited) -- load-time truncation is proven by size gate.
BUNDLE_END_SENTINEL = "<!-- bundle-end -->"

# Matches <!-- bundle: skip-start --> ... <!-- bundle: skip-end --> (incl. the
# trailing newline) so adjacent sections join cleanly. Non-greedy + DOTALL.
SKIP_PATTERN = re.compile(
    r"<!-- bundle: skip-start -->.*?<!-- bundle: skip-end -->\n?",
    flags=re.DOTALL,
)

HEADER = (
    "<!-- Generated by scripts/deploy_agents.py -- do not edit directly.\n"
    "     Source: ai-rules/ai-development-guide.md + rules/<scope: {scopes}>\n"
    "     Regenerate: uv run python scripts/deploy_agents.py -->\n\n"
)


def read_scope(path: pathlib.Path) -> str:
    """Extract harness-scope from YAML frontmatter. Default: neutral."""
    content = path.read_text(encoding="utf-8")
    if not content.startswith("---"):
        return "neutral"
    for line in content.split("\n")[1:]:
        if line.strip() == "---":
            break
        if line.strip().startswith("harness-scope:"):
            scope = line.split(":", 1)[1].strip()
            return scope or "neutral"
    return "neutral"


def discover_rules(
    rules_dir: pathlib.Path, target_scopes: set[str]
) -> list[pathlib.Path]:
    """Scan rules/*.md, return those whose harness-scope is in target_scopes."""
    rules = []
    for path in sorted(rules_dir.glob("*.md")):
        if read_scope(path) in target_scopes:
            rules.append(path)
    return rules


# Match `(Claude: ...)` parenthetical notes, supporting both ASCII `()`
# and full-width `（）` parens (CJK convention). Refs inside these are
# Claude-side pointers non-Claude readers can ignore, so they're stripped
# before scanning. Allows a single level of nested ASCII parens.
_OPEN = r"[\(（]"
_CLOSE = r"[\)）]"
_NOT_PAREN = r"[^()（）]"
CLAUDE_NOTE_PATTERN = re.compile(
    _OPEN
    + r"Claude[:：]"
    + _NOT_PAREN
    + r"*"
    + r"(?:\([^()]*\)"
    + _NOT_PAREN
    + r"*)*"
    + _CLOSE
)

# Markdown link `[text](target.md)` — capture target path.
LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+\.md)\)")

# Backtick-quoted bare rule ref like `` `rule-name.md` ``.
BACKTICK_REF_PATTERN = re.compile(r"`([a-z][a-z0-9_-]*\.md)`")


def scan_sources(rules_dir: pathlib.Path, include_guide: bool) -> list[tuple[str, str]]:
    """Bundle sources as (name, content) pairs, Claude notes stripped.

    Neutral rules always (purity scope per rules/AGENTS.md 機械檢查清單:
    rules/*.md only -- the guide legitimately mentions cross-harness bare
    slash commands like `/handoff`, so it must NOT enter the purity scan).
    Guide included only for broken-ref scanning (it ships in the bundle too).
    rules/AGENTS.md itself is meta-scoped and never enters the neutral set,
    so its self-referential examples cannot false-positive either scan.
    """
    sources = [
        (p.name, p.read_text(encoding="utf-8"))
        for p in discover_rules(rules_dir, {"neutral"})
    ]
    if include_guide and GUIDE.exists():
        sources.append((GUIDE.name, GUIDE.read_text(encoding="utf-8")))
    return [(name, CLAUDE_NOTE_PATTERN.sub("", content)) for name, content in sources]


def check_broken_refs(
    rules_dir: pathlib.Path,
) -> list[tuple[str, str, str]]:
    """Find bundle sources (neutral rules + guide) linking to claude-specific rules.

    Returns a list of (source_name, link_target, target_rule_name) tuples.
    Parenthetical Claude notes `(Claude: ...)` are exempt: their contents are
    stripped before scanning, so refs inside them don't count as broken.

    The scan scope is a global invariant -- it always checks neutral sources
    against claude-specific targets, regardless of what deploy is bundling.
    The guide is scanned since build_bundle ships it verbatim (a guide-side
    ref to a claude-specific file is just as dead for non-Claude readers).
    """
    claude_stems = {p.stem for p in discover_rules(rules_dir, {"claude-specific"})}

    broken: list[tuple[str, str, str]] = []
    for src_name, cleaned in scan_sources(rules_dir, include_guide=True):
        # Markdown links `[text](target.md)`.
        for _, link_target in LINK_PATTERN.findall(cleaned):
            stem = pathlib.Path(link_target).stem
            if stem in claude_stems:
                broken.append((src_name, link_target, stem))
        # Bare backtick refs `` `rule-name.md` ``.
        for match in BACKTICK_REF_PATTERN.finditer(cleaned):
            ref = match.group(1)
            stem = ref[:-3]  # strip ".md"
            if stem in claude_stems:
                broken.append((src_name, ref, stem))
    return broken


# Neutral-purity patterns -- the programmatic form of rules/AGENTS.md's
# 機械檢查清單 (which until 2026-08-30 existed only as prose commands nobody
# ran; two live violations had shipped to all three deployed bundles).
# 已知限制：(1) 掃描面 = 全文，build_bundle 的 slim skip 段不 ship 但仍被掃
# （repo 現無 marker；首個 skip marker 出現時重訪此差異）。(2) bare-slash
# pattern 與 checklist 的 rg 原文逐字等價（僅攔 backtick 形態）。(3)
# claude-wrapper 的豁免詞「Claude 端」為列舉制——寫「Claude Code」等其他
# 措辭會誤抓，屬可接受的 heuristic。
PURITY_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("bare-slash-command", re.compile(r"`/[a-z][a-z-]+[ `]")),
    ("at-transclusion", re.compile(r"@~/|@\.\./|@/[a-z]")),
    ("cross-domain-path", re.compile(r"\.\./(commands|skills)/")),
    ("abs-user-path", re.compile(r"~/Github/ai-rules/")),
]
CLAUDE_WRAPPER_PATTERN = re.compile(r"CLAUDE\.md wrapper")


def check_neutral_purity(rules_dir: pathlib.Path) -> list[tuple[str, str, str]]:
    """Find neutral-rule purity violations (rules/AGENTS.md 機械檢查清單).

    Returns a list of (rule_name, check_label, matched_text) tuples. Input is
    Claude-note-stripped, matching the checklist's 括號注 exemption.
    """
    violations: list[tuple[str, str, str]] = []
    for rule_name, cleaned in scan_sources(rules_dir, include_guide=False):
        for label, pattern in PURITY_PATTERNS:
            for match in pattern.finditer(cleaned):
                violations.append((rule_name, label, match.group(0)))
        for line in cleaned.splitlines():
            if CLAUDE_WRAPPER_PATTERN.search(line) and "Claude 端" not in line:
                violations.append(
                    (rule_name, "claude-wrapper-unannotated", line.strip()[:80])
                )
    return violations


def slim_for_bundle(content: str, rule_name: str = "") -> str:
    """Drop bundle-skip marker sections. No-op when no markers present.

    Warns on unbalanced markers (start without end or vice versa) so future
    edits that drop a marker don't silently skip the slimming.
    """
    starts = content.count("<!-- bundle: skip-start -->")
    ends = content.count("<!-- bundle: skip-end -->")
    if starts != ends:
        loc = f" in {rule_name}" if rule_name else ""
        print(
            f"[WARN] unbalanced bundle markers{loc}: {starts} start vs {ends} end",
            file=sys.stderr,
        )
    return SKIP_PATTERN.sub("", content)


def build_bundle(rule_paths: list[pathlib.Path], scopes_label: str) -> str:
    parts = [HEADER.format(scopes=scopes_label)]
    parts.append(GUIDE.read_text(encoding="utf-8").strip())
    parts.append("")
    for rule_path in rule_paths:
        parts.append(f"\n---\n<!-- rules/{rule_path.name} -->\n")
        parts.append(
            slim_for_bundle(
                rule_path.read_text(encoding="utf-8"), rule_path.name
            ).strip()
        )
        parts.append("")
    parts.append(BUNDLE_END_SENTINEL)
    return "\n".join(parts)


def deploy(target: pathlib.Path, bundle: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not target.is_symlink():
        existing = target.read_text(encoding="utf-8")
        if "Generated by scripts/deploy_agents.py" not in existing:
            backup = target.with_suffix(".md.bak")
            backup.write_text(existing, encoding="utf-8")
            print(f"  [WARN] backed up {target} -> {backup}")
    if target.is_symlink() or target.exists():
        target.unlink()
    target.write_text(bundle, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Deploy bundled AGENTS.md to non-Claude harnesses."
    )
    ap.add_argument(
        "--scope",
        default="neutral",
        help="comma-separated harness-scopes to bundle (default: neutral)",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="preview bundle stats without writing (stats only; use `cat` on a deployed target or import build_bundle to inspect content)",
    )
    args = ap.parse_args()

    target_scopes = {s.strip() for s in args.scope.split(",")}
    scopes_label = ",".join(sorted(target_scopes))

    if not GUIDE.exists():
        print(f"[FAIL] Guide not found: {GUIDE}", file=sys.stderr)
        return 1

    rule_paths = discover_rules(RULES_DIR, target_scopes)
    if not rule_paths:
        print(f"[FAIL] No rules with scope in {target_scopes}", file=sys.stderr)
        return 1

    broken = check_broken_refs(RULES_DIR)
    if broken:
        print(
            f"[FAIL] {len(broken)} broken ref(s): bundle sources linking to claude-specific rules:",
            file=sys.stderr,
        )
        for src, target, name in broken:
            print(f"  {src} -> {target} ({name} is claude-specific)", file=sys.stderr)
        print("Fix the ref, or re-scope the target to neutral.", file=sys.stderr)
        return 1

    impure = check_neutral_purity(RULES_DIR)
    if impure:
        print(
            f"[FAIL] {len(impure)} neutral-purity violation(s) "
            "(rules/AGENTS.md 機械檢查清單):",
            file=sys.stderr,
        )
        for rule_name, label, hit in impure:
            print(f"  {rule_name}: [{label}] {hit}", file=sys.stderr)
        print(
            "Neutralize it: move into a (Claude: ...) note, describe the skill "
            "by name, or generalize the path away.",
            file=sys.stderr,
        )
        return 1

    bundle = build_bundle(rule_paths, scopes_label)
    # Sentinel integrity is the load-time truncation proof; guard it every run.
    assert bundle.count(BUNDLE_END_SENTINEL) == 1
    assert bundle.rstrip().endswith(BUNDLE_END_SENTINEL)
    bundle_lines = bundle.count("\n") + 1
    bundle_bytes = len(bundle.encode("utf-8"))
    tok_est = bundle_bytes // 3200

    rule_names = [p.name for p in rule_paths]
    print(f"[OK] bundle: {len(rule_paths)} rules (scope={scopes_label}) + guide")
    print(f"     rules: {', '.join(rule_names)}")
    print(
        f"     size: {bundle_lines} lines, {bundle_bytes:,} bytes "
        f"(~{tok_est}K tokens est, {bundle_bytes * 100 // BUNDLE_MAX_BYTES}% of "
        f"{BUNDLE_MAX_BYTES // 1024}KiB gate)"
    )

    if bundle_bytes > BUNDLE_MAX_BYTES:
        print(
            f"[FAIL] bundle {bundle_bytes:,} bytes exceeds size gate "
            f"{BUNDLE_MAX_BYTES:,} bytes ({BUNDLE_MAX_BYTES // 1024}KiB)",
            file=sys.stderr,
        )
        print(
            "     Non-Claude harnesses truncate silently (ZCode: 102,400B hard "
            "line). Slim rules/ per encoder-philosophy, or demote on-demand "
            "content to a reference skill (rule keeps always-on core + "
            "pointer; see rules/AGENTS.md size-gate note).",
            file=sys.stderr,
        )
        return 1

    if args.dry_run:
        print("[DRY-RUN] skipping deploy")
        return 0

    deployed = 0
    for target in TARGETS:
        try:
            deploy(target, bundle)
            print(f"  -> {target}")
            deployed += 1
        except Exception as exc:
            print(f"  [FAIL] {target}: {exc}", file=sys.stderr)
    if deployed == len(TARGETS):
        print(f"[OK] deployed to {deployed}/{len(TARGETS)} non-Claude harnesses")
    else:
        print(
            f"[FAIL] deployed to {deployed}/{len(TARGETS)} non-Claude harnesses",
            file=sys.stderr,
        )
    print(
        "     Claude (~/.claude/CLAUDE.md) untouched -- rules via ~/.claude/rules/ auto-load"
    )
    return 0 if deployed == len(TARGETS) else 1


if __name__ == "__main__":
    raise SystemExit(main())
