#!/usr/bin/env python3
"""
Deploy bundled AGENTS.md to non-Claude harnesses.

Bundles ai-development-guide.md (guide) + rules with matching harness-scope
frontmatter -> writes to ~/.zcode/AGENTS.md, ~/.config/opencode/AGENTS.md,
~/.codex/AGENTS.md.

Claude (~/.claude/CLAUDE.md) is NOT touched -- it stays symlink to the
slim guide; Claude gets rules via ~/.claude/rules/ auto-load.

Rule classification is auto-discovered from per-rule frontmatter:
    ---
    harness-scope: neutral
    ---
Scopes: neutral | borderline | claude-specific | meta

Default bundles 'neutral'. Use --scope neutral,borderline for fuller bundle.
Run after editing rules/ (deploy discipline in rules/AGENTS.md). Idempotent.
"""
import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
GUIDE = REPO / "ai-development-guide.md"
RULES_DIR = REPO / "rules"

TARGETS = [
    pathlib.Path.home() / ".zcode" / "AGENTS.md",
    pathlib.Path.home() / ".config" / "opencode" / "AGENTS.md",
    pathlib.Path.home() / ".codex" / "AGENTS.md",
]

HEADER = (
    "<!-- Generated by scripts/deploy_agents.py -- do not edit directly.\n"
    "     Source: ai-rules/ai-development-guide.md + rules/<scope: {scopes}>\n"
    "     Regenerate: uv run python scripts/deploy_agents.py -->\n\n"
)


def read_scope(path: pathlib.Path) -> str:
    """Extract harness-scope from YAML frontmatter. Default: claude-specific."""
    content = path.read_text(encoding="utf-8")
    if not content.startswith("---"):
        return "claude-specific"
    for line in content.split("\n")[1:]:
        if line.strip() == "---":
            break
        if line.strip().startswith("harness-scope:"):
            scope = line.split(":", 1)[1].strip()
            return scope or "claude-specific"
    return "claude-specific"


def discover_rules(rules_dir: pathlib.Path, target_scopes: set[str]) -> list[pathlib.Path]:
    """Scan rules/*.md, return those whose harness-scope is in target_scopes."""
    rules = []
    for path in sorted(rules_dir.glob("*.md")):
        if read_scope(path) in target_scopes:
            rules.append(path)
    return rules


def build_bundle(rule_paths: list[pathlib.Path], scopes_label: str) -> str:
    parts = [HEADER.format(scopes=scopes_label)]
    parts.append(GUIDE.read_text(encoding="utf-8").strip())
    parts.append("")
    for rule_path in rule_paths:
        parts.append(f"\n---\n<!-- rules/{rule_path.name} -->\n")
        parts.append(rule_path.read_text(encoding="utf-8").strip())
        parts.append("")
    return "\n".join(parts)


def deploy(target: pathlib.Path, bundle: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not target.is_symlink():
        existing = target.read_text(encoding="utf-8")
        if "Generated by scripts/deploy_agents.py" not in existing:
            backup = target.with_suffix(".md.bak")
            backup.write_text(existing, encoding="utf-8")
            print(f"  [WARN] backed up {target} -> {backup}")
    if target.is_symlink() or target.exists():
        target.unlink()
    target.write_text(bundle, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Deploy bundled AGENTS.md to non-Claude harnesses.")
    ap.add_argument("--scope", default="neutral",
                    help="comma-separated harness-scopes to bundle (default: neutral)")
    ap.add_argument("--dry-run", action="store_true", help="preview without writing")
    args = ap.parse_args()

    target_scopes = {s.strip() for s in args.scope.split(",")}
    scopes_label = ",".join(sorted(target_scopes))

    if not GUIDE.exists():
        print(f"[FAIL] Guide not found: {GUIDE}", file=sys.stderr)
        return 1

    rule_paths = discover_rules(RULES_DIR, target_scopes)
    if not rule_paths:
        print(f"[FAIL] No rules with scope in {target_scopes}", file=sys.stderr)
        return 1

    bundle = build_bundle(rule_paths, scopes_label)
    bundle_lines = bundle.count("\n") + 1
    bundle_bytes = len(bundle.encode("utf-8"))
    tok_est = bundle_bytes // 3200

    rule_names = [p.name for p in rule_paths]
    print(f"[OK] bundle: {len(rule_paths)} rules (scope={scopes_label}) + guide")
    print(f"     rules: {', '.join(rule_names)}")
    print(f"     size: {bundle_lines} lines, {bundle_bytes:,} bytes (~{tok_est}K tokens est)")

    if args.dry_run:
        print("[DRY-RUN] skipping deploy")
        return 0

    deployed = 0
    for target in TARGETS:
        try:
            deploy(target, bundle)
            print(f"  -> {target}")
            deployed += 1
        except Exception as exc:
            print(f"  [FAIL] {target}: {exc}", file=sys.stderr)
    print(f"[OK] deployed to {deployed}/{len(TARGETS)} non-Claude harnesses")
    print(f"     Claude (~/.claude/CLAUDE.md) untouched -- rules via ~/.claude/rules/ auto-load")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
