#!/usr/bin/env python3
"""
Deploy bundled AGENTS.md to non-Claude harnesses.

Bundles ai-development-guide.md (guide) + rules with matching harness-scope
frontmatter -> writes to ~/.zcode/AGENTS.md, ~/.config/opencode/AGENTS.md,
~/.codex/AGENTS.md.

Claude (~/.claude/CLAUDE.md) is NOT touched -- it stays symlink to the
slim guide; Claude gets rules via ~/.claude/rules/ auto-load.

Rule classification is auto-discovered from per-rule frontmatter:
    ---
    harness-scope: neutral
    ---
Scopes: neutral | claude-specific | meta

Default bundles 'neutral'. New rules without an explicit harness-scope
default to 'neutral' (generic knowledge defaults to cross-harness). Rules
that are Claude-specific must declare `harness-scope: claude-specific`
explicitly to be excluded from the bundle.

Broken-ref guard: scans every neutral rule's markdown links; if a neutral
rule links to a claude-specific rule, the deploy aborts with an error
listing each broken ref. This forces fixing the ref (or re-scoping the
target) before the bundle ships -- non-Claude readers would otherwise hit
a dead link. Parenthetical Claude notes `(Claude: ...)` are exempt, since
those are Claude-side pointers that non-Claude readers can ignore.

Bundle slimming: rule bodies may mark sections to drop from the bundle with
    <!-- bundle: skip-start --> ... <!-- bundle: skip-end -->
Claude reads the full file via ~/.claude/rules/ symlink; non-Claude bundles
get the slimmed version. No-op for rules without markers.

Run after editing rules/ (deploy discipline in rules/AGENTS.md). Idempotent.
"""
import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
GUIDE = REPO / "ai-development-guide.md"
RULES_DIR = REPO / "rules"

TARGETS = [
    pathlib.Path.home() / ".zcode" / "AGENTS.md",
    pathlib.Path.home() / ".config" / "opencode" / "AGENTS.md",
    pathlib.Path.home() / ".codex" / "AGENTS.md",
]

# Matches <!-- bundle: skip-start --> ... <!-- bundle: skip-end --> (incl. the
# trailing newline) so adjacent sections join cleanly. Non-greedy + DOTALL.
SKIP_PATTERN = re.compile(
    r"<!-- bundle: skip-start -->.*?<!-- bundle: skip-end -->\n?",
    flags=re.DOTALL,
)

HEADER = (
    "<!-- Generated by scripts/deploy_agents.py -- do not edit directly.\n"
    "     Source: ai-rules/ai-development-guide.md + rules/<scope: {scopes}>\n"
    "     Regenerate: uv run python scripts/deploy_agents.py -->\n\n"
)


def read_scope(path: pathlib.Path) -> str:
    """Extract harness-scope from YAML frontmatter. Default: neutral."""
    content = path.read_text(encoding="utf-8")
    if not content.startswith("---"):
        return "neutral"
    for line in content.split("\n")[1:]:
        if line.strip() == "---":
            break
        if line.strip().startswith("harness-scope:"):
            scope = line.split(":", 1)[1].strip()
            return scope or "neutral"
    return "neutral"


def discover_rules(rules_dir: pathlib.Path, target_scopes: set[str]) -> list[pathlib.Path]:
    """Scan rules/*.md, return those whose harness-scope is in target_scopes."""
    rules = []
    for path in sorted(rules_dir.glob("*.md")):
        if read_scope(path) in target_scopes:
            rules.append(path)
    return rules


# Match `(Claude: ...)` parenthetical notes, supporting both ASCII `()`
# and full-width `（）` parens (CJK convention). Refs inside these are
# Claude-side pointers non-Claude readers can ignore, so they're stripped
# before scanning. Allows a single level of nested ASCII parens.
_OPEN = r"[\(（]"
_CLOSE = r"[\)）]"
_NOT_PAREN = r"[^()（）]"
CLAUDE_NOTE_PATTERN = re.compile(
    _OPEN
    + r"Claude[:：]"
    + _NOT_PAREN + r"*"
    + r"(?:\([^()]*\)" + _NOT_PAREN + r"*)*"
    + _CLOSE
)

# Markdown link `[text](target.md)` — capture target path.
LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+\.md)\)")

# Backtick-quoted bare rule ref like `` `rule-name.md` ``.
BACKTICK_REF_PATTERN = re.compile(r"`([a-z][a-z0-9_-]*\.md)`")


def check_broken_refs(
    rules_dir: pathlib.Path,
) -> list[tuple[str, str, str]]:
    """Find neutral rules that link to claude-specific rules.

    Returns a list of (source_rule_name, link_target, target_rule_name) tuples.
    Parenthetical Claude notes `(Claude: ...)` are exempt: their contents are
    stripped before scanning, so refs inside them don't count as broken.

    The scan scope is a global invariant -- it always checks neutral sources
    against claude-specific targets, regardless of what deploy is bundling.
    """
    neutral_rules = discover_rules(rules_dir, {"neutral"})
    claude_rules = discover_rules(rules_dir, {"claude-specific"})
    claude_stems = {p.stem for p in claude_rules}

    broken: list[tuple[str, str, str]] = []
    for nrule in neutral_rules:
        content = nrule.read_text(encoding="utf-8")
        # Strip parenthetical Claude notes so refs inside them are ignored.
        cleaned = CLAUDE_NOTE_PATTERN.sub("", content)
        # Markdown links `[text](target.md)`.
        for _, link_target in LINK_PATTERN.findall(cleaned):
            stem = pathlib.Path(link_target).stem
            if stem in claude_stems:
                broken.append((nrule.name, link_target, stem))
        # Bare backtick refs `` `rule-name.md` ``.
        for match in BACKTICK_REF_PATTERN.finditer(cleaned):
            ref = match.group(1)
            stem = ref[:-3]  # strip ".md"
            if stem in claude_stems:
                broken.append((nrule.name, ref, stem))
    return broken


def slim_for_bundle(content: str, rule_name: str = "") -> str:
    """Drop bundle-skip marker sections. No-op when no markers present.

    Warns on unbalanced markers (start without end or vice versa) so future
    edits that drop a marker don't silently skip the slimming.
    """
    starts = content.count("<!-- bundle: skip-start -->")
    ends = content.count("<!-- bundle: skip-end -->")
    if starts != ends:
        loc = f" in {rule_name}" if rule_name else ""
        print(f"[WARN] unbalanced bundle markers{loc}: {starts} start vs {ends} end",
              file=sys.stderr)
    return SKIP_PATTERN.sub("", content)


def build_bundle(rule_paths: list[pathlib.Path], scopes_label: str) -> str:
    parts = [HEADER.format(scopes=scopes_label)]
    parts.append(GUIDE.read_text(encoding="utf-8").strip())
    parts.append("")
    for rule_path in rule_paths:
        parts.append(f"\n---\n<!-- rules/{rule_path.name} -->\n")
        parts.append(slim_for_bundle(rule_path.read_text(encoding="utf-8"), rule_path.name).strip())
        parts.append("")
    return "\n".join(parts)


def deploy(target: pathlib.Path, bundle: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not target.is_symlink():
        existing = target.read_text(encoding="utf-8")
        if "Generated by scripts/deploy_agents.py" not in existing:
            backup = target.with_suffix(".md.bak")
            backup.write_text(existing, encoding="utf-8")
            print(f"  [WARN] backed up {target} -> {backup}")
    if target.is_symlink() or target.exists():
        target.unlink()
    target.write_text(bundle, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Deploy bundled AGENTS.md to non-Claude harnesses.")
    ap.add_argument("--scope", default="neutral",
                    help="comma-separated harness-scopes to bundle (default: neutral)")
    ap.add_argument("--dry-run", action="store_true",
                    help="preview bundle stats without writing (stats only; use `cat` on a deployed target or import build_bundle to inspect content)")
    args = ap.parse_args()

    target_scopes = {s.strip() for s in args.scope.split(",")}
    scopes_label = ",".join(sorted(target_scopes))

    if not GUIDE.exists():
        print(f"[FAIL] Guide not found: {GUIDE}", file=sys.stderr)
        return 1

    rule_paths = discover_rules(RULES_DIR, target_scopes)
    if not rule_paths:
        print(f"[FAIL] No rules with scope in {target_scopes}", file=sys.stderr)
        return 1

    broken = check_broken_refs(RULES_DIR)
    if broken:
        print(f"[FAIL] {len(broken)} broken ref(s): neutral rules linking to claude-specific rules:",
              file=sys.stderr)
        for src, target, name in broken:
            print(f"  {src} -> {target} ({name} is claude-specific)", file=sys.stderr)
        print("Fix the ref, or re-scope the target to neutral.", file=sys.stderr)
        return 1

    bundle = build_bundle(rule_paths, scopes_label)
    bundle_lines = bundle.count("\n") + 1
    bundle_bytes = len(bundle.encode("utf-8"))
    tok_est = bundle_bytes // 3200

    rule_names = [p.name for p in rule_paths]
    print(f"[OK] bundle: {len(rule_paths)} rules (scope={scopes_label}) + guide")
    print(f"     rules: {', '.join(rule_names)}")
    print(f"     size: {bundle_lines} lines, {bundle_bytes:,} bytes (~{tok_est}K tokens est)")

    if args.dry_run:
        print("[DRY-RUN] skipping deploy")
        return 0

    deployed = 0
    for target in TARGETS:
        try:
            deploy(target, bundle)
            print(f"  -> {target}")
            deployed += 1
        except Exception as exc:
            print(f"  [FAIL] {target}: {exc}", file=sys.stderr)
    print(f"[OK] deployed to {deployed}/{len(TARGETS)} non-Claude harnesses")
    print(f"     Claude (~/.claude/CLAUDE.md) untouched -- rules via ~/.claude/rules/ auto-load")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
