#!/usr/bin/env python3
"""Project agents/roles/ (authoring single source) into per-harness registries.

roles/ 是 authoring 單一源（frontmatter 白名單 name/description/tools/
background，零 model／harness 字樣）；agents/zcode/ 與 agents/claude/ 是
generator 管理的生成物（ownership marker 標記）。model 值單一源＝
skills/model-routing/SKILL.md tier×provider 權威表；本檔的 dicts 是部署
預設，runtime 以 check_parity 對該表 parity guard（requirement 分配＋
ZCODE_PINS 值雙層）。

安全模型：compute-then-apply——check/map 在任何 mkdir/write/unlink 前
return（零寫入）；sync 才進 mutation boundary。寫入走 temp file＋
os.replace（原子——撕裂態不留 marker 半損殘骸）。stale cleanup 只刪
marker-owned；unmarked 同名檔一律 fail（唯一例外＝一次性 --adopt-legacy
對固定 legacy 路徑、expected 減 marker 後逐檔 exact bytes 相等者——
一次性模式，首次遷移完成後不再使用）。
"""

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path

OWNERSHIP_MARKER = "<!-- generated by scripts/sync_agents.py; do not edit -->"

# tier 詞＝requirement token（full/vision/lite）；分配單一源＝model-routing
# skill「role → requirement（tier）分配表」（check_parity 對其 guard）
ROLE_REQUIREMENTS: dict[str, str] = {
    "archify-gen": "lite",
    "code-reviewer": "lite",
    "code-reviewer-primed": "lite",
    "cr-research": "lite",
    "cross-verify-investigator": "lite",
    "impl-lite": "lite",
    "lite-verify": "lite",
    "mem-distill": "lite",
    "spec-miner": "lite",
    "vision-review": "vision",
}

# ZCode 部署預設 pins（值抄 skill tier×provider 權威表 zai 欄——
# check_parity 逐 tier 機械比對，改表不改 dict → fail）；
# full＝旗艦釘選（AIR-43 inherit 洞修補：unpinned 會跟主 session 漂移）
ZCODE_PINS: dict[str, tuple[str, str]] = {
    "full": ("glm-5.3", "high"),
    "lite": ("glm-5.3-flash", "high"),
    "vision": ("glm-5.3-flash", "high"),
}

# CC 端部署預設（別名層——值抄 skill 權威表 Anthropic 欄首 token，check_parity
# 對其 guard）。別名可攜：env 映射（ANTHROPIC_DEFAULT_*）切 provider 時 alias
# 直接可用、免重釘。effort＝CC spawn-time enum 非 frontmatter，故僅 model。
CLAUDE_PINS: dict[str, str] = {"full": "opus"}

# CC 端 CR MCP 白名單是 ZCode-only 接線（known divergence：claude 拷貝剝除）
CR_MCP_PREFIX = "mcp__plugin_code-reality_code-reality__"

# 首次遷移的 legacy unmarked 輸出（AIR-28 前手動 cp 拓撲殘留）；
# --adopt-legacy 僅收編這些路徑，完成後不再使用
LEGACY_REVIEWER_OUTPUTS = {
    "agents/zcode/code-reviewer.md",
    "agents/zcode/code-reviewer-primed.md",
    "agents/claude/code-reviewer.md",
    "agents/claude/code-reviewer-primed.md",
}

PARITY_SOURCE = Path("skills/model-routing/SKILL.md")
_TIER_TOKENS = {"full", "vision", "lite"}
_ROLE_REQ_HEADING = "## role → requirement"
_TIER_TABLE_HEADING = "## tier → (model, effort)"
_ZAI_PIN_RE = re.compile(
    r"^\|\s*\*{0,2}(full|lite|vision)\*{0,2}（.*?）\s*\|\s*`?([a-z0-9.\-]+)`?"
)
# full 行 Anthropic 欄首 token（別名）——zai 欄 [^|\n]* 不得含 "|"（表 cell
# 註記用〔〕不用（）的慣例防跨欄回溯，AIR-44 實證）
_ANTHROPIC_ALIAS_RE = re.compile(
    r"^\|\s*\*{0,2}full\*{0,2}（.*?）\s*\|[^|\n]*\|\s*`?([a-z0-9.\-]+)`?"
)
_EFFORT_RE = re.compile(r"thoughtLevel: ([a-z]+)")


def _section(text: str, heading: str) -> str:
    """取 heading 之後到下一個同級/更上層標題前的段落（parser 錨定範圍）。"""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip().startswith(heading):
            start = i + 1
            break
    if start is None:
        return ""
    out: list[str] = []
    for line in lines[start:]:
        if line.startswith("#"):
            break
        out.append(line)
    return "\n".join(out)


def parse_skill_role_requirements(skill_text: str) -> dict[str, str]:
    """解析 skill「role → requirement（tier）分配表」（段落錨定——只掃該表）。"""
    table: dict[str, str] = {}
    for line in _section(skill_text, _ROLE_REQ_HEADING).splitlines():
        parts = [p.strip() for p in line.strip().strip("|").split("|")]
        if len(parts) == 2 and parts[0] in _TIER_TOKENS:
            for role in parts[1].split(","):
                role = role.strip()
                # role 必為 slug（拒絣散文格）
                if role and role.replace("-", "").isalnum() and role.isascii():
                    table[role] = parts[0]
    return table


def parse_skill_zai_pins(skill_text: str) -> dict[str, str]:
    """萃取 tier×provider 權威表 zai 欄的 model id（段落錨定——只掃該表）。"""
    pins: dict[str, str] = {}
    for line in _section(skill_text, _TIER_TABLE_HEADING).splitlines():
        m = _ZAI_PIN_RE.match(line.strip())
        if m:
            pins[m.group(1)] = m.group(2)
    return pins


def parse_skill_effort(skill_text: str) -> str | None:
    """萃取部署填法表的 thoughtLevel 值（全 tier 共用一值）。"""
    m = _EFFORT_RE.search(skill_text)
    return m.group(1) if m else None


def parse_skill_anthropic_alias(skill_text: str) -> str | None:
    """萃取權威表 full 行 Anthropic 欄首 token（CC 別名釘選的 parity 鍵）。"""
    for line in _section(skill_text, _TIER_TABLE_HEADING).splitlines():
        m = _ANTHROPIC_ALIAS_RE.match(line.strip())
        if m:
            return m.group(1)
    return None


def check_parity(repo: Path) -> list[str]:
    """dicts ↔ skill 權威表 parity（真 repo 呼叫；drift 清單）。

    雙層：① role→requirement 分配 ② ZCODE_PINS 的 model 值 ↔ 權威表 zai 欄
    （值層——provider 換代改表不改 dict 時在此 fail，不靜默上線舊 pin）。
    """
    skill_text = (repo / PARITY_SOURCE).read_text(encoding="utf-8")
    skill_table = parse_skill_role_requirements(skill_text)
    drift = [
        f"{role}: dict={req} skill={skill_table.get(role)}"
        for role, req in sorted(ROLE_REQUIREMENTS.items())
        if skill_table.get(role) != req
    ]
    extra = set(skill_table) - set(ROLE_REQUIREMENTS)
    missing = set(ROLE_REQUIREMENTS) - set(skill_table)
    if extra:
        drift.append(f"skill-only roles: {sorted(extra)}")
    if missing:
        drift.append(f"dict-only roles: {sorted(missing)}")
    zai_pins = parse_skill_zai_pins(skill_text)
    for tier, (model, _thought) in sorted(ZCODE_PINS.items()):
        if tier in zai_pins and zai_pins[tier] != model:
            drift.append(
                f"ZCODE_PINS[{tier}]={model} but skill zai column={zai_pins[tier]}"
            )
    for tier in sorted(set(ZCODE_PINS) - set(zai_pins)):
        drift.append(
            f"ZCODE_PINS[{tier}] 有值但 skill 權威表 zai 欄未解析到——確認表格仍在"
        )
    anthropic_alias = parse_skill_anthropic_alias(skill_text)
    if anthropic_alias is None:
        drift.append(
            "CLAUDE_PINS 有值但 skill 權威表 Anthropic 欄未解析到——確認表格仍在"
        )
    else:
        for tier, alias in sorted(CLAUDE_PINS.items()):
            if anthropic_alias != alias:
                drift.append(
                    f"CLAUDE_PINS[{tier}]={alias} but skill anthropic column={anthropic_alias}"
                )
    skill_effort = parse_skill_effort(skill_text)
    if skill_effort is not None:
        for tier, (_model, thought) in sorted(ZCODE_PINS.items()):
            if thought != skill_effort:
                drift.append(
                    f"ZCODE_PINS[{tier}].thoughtLevel={thought} "
                    f"but skill 部署填法表={skill_effort}"
                )
    return drift


def load_role_specs(repo: Path) -> dict[str, str]:
    role_dir = repo / "agents" / "roles"
    return {
        path.stem: path.read_text(encoding="utf-8")
        for path in sorted(role_dir.glob("*.md"))
    }


_FRONTMATTER_ALLOWLIST = {"name", "description", "tools", "background"}


def split_frontmatter(role_name: str, role_body: str) -> tuple[str, str]:
    """前置驗證＋切分 frontmatter/body（BOM／缺 frontmatter／空 frontmatter 分別報）。"""
    if role_body.startswith("\ufeff"):
        raise AssertionError(f"{role_name}: frontmatter 前有 BOM——去掉後重存")
    if not role_body.startswith("---\n"):
        raise AssertionError(f"{role_name}: 缺 frontmatter（首行必須是 ---）")
    if role_body.startswith("---\n---\n"):
        raise AssertionError(
            f"{role_name}: frontmatter 為空（至少需 name/description）"
        )
    frontmatter, separator, body = role_body[4:].partition("\n---\n")
    if not separator:
        raise AssertionError(f"{role_name}: frontmatter 未閉合（缺 --- 結尾欄）")
    if not frontmatter.strip():
        raise AssertionError(
            f"{role_name}: frontmatter 為空（至少需 name/description）"
        )
    keys = {
        line.split(":", 1)[0].strip()
        for line in frontmatter.splitlines()
        if line.strip()
    }
    illegal = keys - _FRONTMATTER_ALLOWLIST
    if illegal:
        raise AssertionError(
            f"{role_name}: frontmatter 鍵 {sorted(illegal)} 超出白名單 "
            f"{sorted(_FRONTMATTER_ALLOWLIST)}（model/thoughtLevel 屬投影層——pins 由 sync 生成）"
        )
    return frontmatter, body


def project_tools(frontmatter: str, target: str) -> str:
    lines: list[str] = []
    for line in frontmatter.splitlines():
        if target == "claude" and line.startswith("tools:"):
            key, raw_tools = line.split(":", maxsplit=1)
            tools = [tool.strip() for tool in raw_tools.split(",")]
            tools = [
                tool for tool in tools if tool and not tool.startswith(CR_MCP_PREFIX)
            ]
            if not tools:
                raise AssertionError(
                    "claude 投影後 tools 全空（源 tools 只有 CR MCP 全名？）"
                    "—— CC 端語義未定義，先修 roles/ 源補非 CR tools"
                )
            line = f"{key}: {', '.join(tools)}"
        lines.append(line)
    return "\n".join(lines)


def render_registry(
    role_name: str,
    role_body: str,
    target: str,
    requirement: str,
) -> str:
    frontmatter, body = split_frontmatter(role_name, role_body)
    frontmatter = project_tools(frontmatter, target)
    target_fields = ""
    if target == "zcode" and requirement in ZCODE_PINS:
        model, thought_level = ZCODE_PINS[requirement]
        target_fields = f"\nmodel: {model}\nthoughtLevel: {thought_level}"
    elif target == "claude" and requirement in CLAUDE_PINS:
        target_fields = f"\nmodel: {CLAUDE_PINS[requirement]}"
    return f"---\n{frontmatter}{target_fields}\n---\n{OWNERSHIP_MARKER}\n{body}"


def is_owned(file_text: str) -> bool:
    if not file_text.startswith("---\n"):
        return False
    _, separator, body = file_text[4:].partition("\n---\n")
    return bool(separator) and body.startswith(f"{OWNERSHIP_MARKER}\n")


def without_marker(file_text: str) -> str:
    return file_text.replace(f"{OWNERSHIP_MARKER}\n", "", 1)


def expected_projections(
    repo: Path,
    requirements: dict[str, str] | None = None,
) -> dict[Path, str]:
    policy = ROLE_REQUIREMENTS if requirements is None else requirements
    roles = load_role_specs(repo)
    assert roles.keys() == policy.keys(), (
        f"roles/policy mismatch — roles-only: {sorted(set(roles) - set(policy))}, "
        f"policy-only: {sorted(set(policy) - set(roles))}"
    )
    expected: dict[Path, str] = {}
    for target in ("zcode", "claude"):
        for name, body in roles.items():
            rendered = render_registry(name, body, target, policy[name])
            expected[repo / "agents" / target / f"{name}.md"] = rendered
    return expected


def inventory_owned_outputs(repo: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for target in ("zcode", "claude"):
        for path in sorted((repo / "agents" / target).glob("*.md")):
            file_text = path.read_text(encoding="utf-8")
            if is_owned(file_text):
                outputs[path] = file_text
    return outputs


def compare_projection(
    expected: dict[Path, str],
    owned: dict[Path, str],
) -> list[Path]:
    paths = set(expected) | set(owned)
    return sorted(path for path in paths if expected.get(path) != owned.get(path))


def validate_collisions(
    expected: dict[Path, str],
    *,
    adopt_legacy: bool,
    legacy_paths: set[str] | None = None,
) -> None:
    allowlist = LEGACY_REVIEWER_OUTPUTS if legacy_paths is None else legacy_paths
    collisions = [
        path
        for path in expected
        if path.exists()
        and not is_owned(path.read_text(encoding="utf-8"))
        and (
            not adopt_legacy
            or "/".join(path.parts[-3:]) not in allowlist
            or without_marker(expected[path]) != path.read_text(encoding="utf-8")
        )
    ]
    assert not collisions, f"unmarked same-name outputs block sync: {collisions}"


def atomic_write(path: Path, file_text: str) -> None:
    """temp file + os.replace——撕裂中斷不留半損檔（marker 半損會卡死後續 sync）。"""
    fd, tmp_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(file_text)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def apply_projection(
    expected: dict[Path, str],
    owned: dict[Path, str],
    *,
    adopt_legacy: bool = False,
    legacy_paths: set[str] | None = None,
) -> None:
    validate_collisions(expected, adopt_legacy=adopt_legacy, legacy_paths=legacy_paths)
    for path, file_text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if owned.get(path) != file_text:
            atomic_write(path, file_text)
    for stale in set(owned) - set(expected):
        stale.unlink()


def render_map(
    expected: dict[Path, str],
    requirements: dict[str, str] | None = None,
    owned: dict[Path, str] | None = None,
) -> str:
    """role/requirement/zcode/claude 四欄——registry 欄反映磁碟現況（owned 導出）。"""
    policy = ROLE_REQUIREMENTS if requirements is None else requirements
    on_disk = (
        {(path.parent.name, path.stem) for path in owned}
        if owned is not None
        else {(path.parent.name, path.stem) for path in expected}
    )
    rows = ["role\trequirement\tzcode\tclaude"]
    for role in sorted(policy):
        requirement = policy[role]
        zcode = "yes" if ("zcode", role) in on_disk else "no"
        claude = "yes" if ("claude", role) in on_disk else "no"
        rows.append(f"{role}\t{requirement}\t{zcode}\t{claude}")
    return "\n".join(rows)


_MODES = {"check", "map", "sync", "adopt-legacy"}


def main(
    repo: Path,
    *,
    mode: str,
    requirements: dict[str, str] | None = None,
    legacy_paths: set[str] | None = None,
) -> int:
    """exit 語義：0=綠、1=drift（生成物 vs 源，重跑 sync 可修）、2=fatal
    （parity/mismatch——policy 或 skill 表要改，sync 修不了）、3=parity 未驗證
    （PARITY_SOURCE 缺席＋投影一致——checkout 不完整；非綠：registry bytes
    一致但 policy parity 無從校驗，checker 端據此分級）。"""
    assert mode in _MODES, f"unknown mode: {mode}（合法：{sorted(_MODES)}）"
    parity_unverified = False
    if requirements is None:
        if (repo / PARITY_SOURCE).exists():
            parity_drift = check_parity(repo)
            if parity_drift:
                print(f"parity drift vs {PARITY_SOURCE}:", file=sys.stderr)
                for line in parity_drift:
                    print(f"  {line}", file=sys.stderr)
                return 2
        else:
            parity_unverified = True
            print(f"[WARN] parity source 缺席（{PARITY_SOURCE}）——parity 未驗證")
    try:
        expected = expected_projections(repo, requirements)
    except AssertionError as exc:
        print(f"fatal (roles/policy mismatch): {exc}", file=sys.stderr)
        return 2
    owned = inventory_owned_outputs(repo)
    drift = compare_projection(expected, owned)
    if mode == "check":
        for path in drift:
            print(path)
        if drift:
            return 1
        return 3 if parity_unverified else 0
    if mode == "map":
        print(render_map(expected, requirements, owned))
        return 0
    apply_projection(
        expected,
        owned,
        adopt_legacy=mode == "adopt-legacy",
        legacy_paths=legacy_paths,
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check", action="store_true", help="唯讀比對，drift 列清單 exit 1"
    )
    group.add_argument("--map", action="store_true", help="印 role→registry 可用性表")
    group.add_argument(
        "--adopt-legacy", action="store_true", help="一次性收編 legacy unmarked 輸出"
    )
    args = parser.parse_args()
    mode = (
        "check"
        if args.check
        else "map"
        if args.map
        else "adopt-legacy"
        if args.adopt_legacy
        else "sync"
    )
    raise SystemExit(main(Path(__file__).resolve().parents[1], mode=mode))
